spring.application.name=SpringBoot_skill_6
server.port=2006

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/skill6?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=H@r$hA#0812*2006!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect